# Generated by Django 4.0.3 on 2022-08-22 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import saratingsapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=saratingsapp.models.doc_upload_location)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_upload',
            },
        ),
    ]
