# Generated by Django 4.0.4 on 2022-09-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saratingsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAREvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.CharField(blank=True, max_length=100, null=True)),
                ('event_venue', models.CharField(blank=True, max_length=100, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('agenda_item_1', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_2', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_3', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_4', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_5', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_6', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_7', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_8', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_9', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_10', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_11', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_12', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_13', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_14', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda_item_15', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'SAR Events',
                'db_table': 'sar_event',
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email_address', models.EmailField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=100, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saratingsapp.sarevents')),
            ],
            options={
                'verbose_name_plural': 'Events RSVP',
                'db_table': 'event_rsvp',
            },
        ),
    ]
