# Generated by Django 4.0.4 on 2022-09-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saratingsapp', '0002_sarevents_eventrsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarevents',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
