# Generated by Django 4.0.4 on 2022-09-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saratingsapp', '0003_alter_sarevents_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrsvp',
            name='confirm_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
