# Generated by Django 4.0.4 on 2022-09-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saratingsapp', '0004_eventrsvp_confirm_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarevents',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
