# Generated by Django 4.0.4 on 2022-09-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saratingsapp', '0005_sarevents_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarevents',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
