# Generated by Django 4.0.4 on 2022-09-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saratingsapp', '0006_sarevents_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarevents',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
