# Generated by Django 4.0.4 on 2022-09-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saratingsapp', '0007_sarevents_event_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SAREvents',
            new_name='SAREvent',
        ),
    ]
