# Generated by Django 4.0.4 on 2022-09-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saratingsapp', '0008_rename_sarevents_sarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrsvp',
            name='confirm_attendance',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
